name: Impellor V1 Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
        vcpkgGitCommitId: "4f14f0f2f7778caaef08a3e021eae4375f2e1f02"
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Run binary
      run: .\build\Impellor.exe
